# Generated by Django 2.2 on 2021-04-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoReadsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
    ]
