# Generated by Django 2.2 on 2021-04-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
