# Generated by Django 2.2 on 2021-04-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='books_authors_app.Book'),
        ),
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
